import type { Property } from './property';

export const propertiesMock: Property[] = [
  // ---------- São Paulo ----------
  {
    id: '1',
    title: 'Apto moderno com varanda gourmet — Vila Madalena',
    description: 'Apartamento reformado com varanda gourmet, próximo ao metrô.',
    type: 'APARTMENT',
    street: 'Rua Harmonia',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '05435-000',
    bedrooms: 3,
    bathrooms: 2,
    parkingSpots: 1,
    areaM2: 85,
    rentPrice: 3000,
    condoFee: 450,
    iptu: 120,
    status: 'AVAILABLE',
    listingType: 'RENT',
  },
  {
    id: '2',
    title: 'Studio compacto e luminoso na Faria Lima',
    description: 'Studio bem localizado, ideal para quem trabalha na região.',
    type: 'STUDIO',
    street: 'Av. Faria Lima',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '05426-100',
    bedrooms: 1,
    bathrooms: 1,
    parkingSpots: 1,
    areaM2: 42,
    salePrice: 750000,
    condoFee: 780,
    iptu: 90,
    status: 'AVAILABLE',
    listingType: 'SALE',
  },
  {
    id: '3',
    title: 'Apartamento reformado próximo ao metrô Sumaré',
    description: 'Dois quartos, reformado, próximo ao metrô Sumaré.',
    type: 'APARTMENT',
    street: 'Rua Sumaré',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01254-000',
    bedrooms: 2,
    bathrooms: 1,
    parkingSpots: 1,
    areaM2: 68,
    rentPrice: 2900,
    condoFee: 540,
    iptu: 100,
    status: 'AVAILABLE',
    listingType: 'RENT',
  },
  {
    id: '4',
    title: 'Casa térrea com quintal — Vila Mariana',
    description: 'Casa térrea com quintal amplo, ótima para famílias.',
    type: 'HOUSE',
    street: 'Rua Domingos de Morais',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '04010-000',
    bedrooms: 3,
    bathrooms: 2,
    parkingSpots: 2,
    areaM2: 140,
    salePrice: 980000,
    condoFee: 0,
    iptu: 210,
    status: 'AVAILABLE',
    listingType: 'SALE',
  },
  {
    id: '5',
    title: 'Studio novo próximo à USP — Butantã',
    description: 'Studio em prédio novo, ideal para estudantes.',
    type: 'STUDIO',
    street: 'Rua Butantã',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '05502-001',
    bedrooms: 1,
    bathrooms: 1,
    parkingSpots: 0,
    areaM2: 28,
    rentPrice: 1800,
    condoFee: 350,
    iptu: 60,
    status: 'AVAILABLE',
    listingType: 'RENT',
  },
  {
    id: '6',
    title: 'Apartamento amplo com vista — Moema',
    description: 'Três quartos com suíte, próximo ao Parque Ibirapuera.',
    type: 'APARTMENT',
    street: 'Av. Ibirapuera',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '04029-000',
    bedrooms: 3,
    bathrooms: 3,
    parkingSpots: 2,
    areaM2: 120,
    salePrice: 1450000,
    condoFee: 980,
    iptu: 340,
    status: 'AVAILABLE',
    listingType: 'SALE',
  },
  {
    id: '7',
    title: 'Casa sobrado em condomínio fechado — Santo Amaro',
    description: 'Sobrado com quintal, área de lazer e segurança 24h.',
    type: 'HOUSE',
    street: 'Rua Santo Amaro',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '04701-000',
    bedrooms: 4,
    bathrooms: 3,
    parkingSpots: 2,
    areaM2: 180,
    rentPrice: 6500,
    condoFee: 600,
    iptu: 380,
    status: 'AVAILABLE',
    listingType: 'RENT',
  },
  {
    id: '8',
    title: 'Apartamento econômico na Mooca',
    description: 'Dois quartos, próximo ao comércio e transporte público.',
    type: 'APARTMENT',
    street: 'Rua da Mooca',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '03103-000',
    bedrooms: 2,
    bathrooms: 1,
    parkingSpots: 1,
    areaM2: 60,
    salePrice: 520000,
    condoFee: 380,
    iptu: 80,
    status: 'AVAILABLE',
    listingType: 'SALE',
  },
  {
    id: '9',
    title: 'Studio mobiliado na Bela Vista',
    description: 'Studio totalmente mobiliado, pronto para morar.',
    type: 'STUDIO',
    street: 'Rua Major Sertório',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01222-000',
    bedrooms: 1,
    bathrooms: 1,
    parkingSpots: 0,
    areaM2: 35,
    rentPrice: 2400,
    condoFee: 420,
    iptu: 70,
    status: 'AVAILABLE',
    listingType: 'RENT',
  },

  // ---------- Rio de Janeiro ----------
  {
    id: '10',
    title: 'Apartamento com vista mar — Copacabana',
    description: 'Dois quartos com varanda e vista para o mar.',
    type: 'APARTMENT',
    street: 'Av. Atlântica',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '22021-001',
    bedrooms: 2,
    bathrooms: 2,
    parkingSpots: 1,
    areaM2: 75,
    salePrice: 1100000,
    condoFee: 850,
    iptu: 220,
    status: 'AVAILABLE',
    listingType: 'SALE',
  },
  {
    id: '11',
    title: 'Studio próximo à praia — Ipanema',
    description: 'Studio compacto a poucos metros da praia de Ipanema.',
    type: 'STUDIO',
    street: 'Rua Visconde de Pirajá',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '22410-002',
    bedrooms: 1,
    bathrooms: 1,
    parkingSpots: 0,
    areaM2: 32,
    rentPrice: 3200,
    condoFee: 600,
    iptu: 150,
    status: 'AVAILABLE',
    listingType: 'RENT',
  },
  {
    id: '12',
    title: 'Casa em condomínio — Barra da Tijuca',
    description: 'Casa ampla com quintal, piscina e área de lazer.',
    type: 'HOUSE',
    street: 'Av. das Américas',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '22640-100',
    bedrooms: 4,
    bathrooms: 4,
    parkingSpots: 3,
    areaM2: 220,
    salePrice: 1800000,
    condoFee: 1200,
    iptu: 450,
    status: 'AVAILABLE',
    listingType: 'SALE',
  },
  {
    id: '13',
    title: 'Apartamento reformado — Botafogo',
    description: 'Dois quartos reformados, próximo ao metrô Botafogo.',
    type: 'APARTMENT',
    street: 'Rua Voluntários da Pátria',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '22270-000',
    bedrooms: 2,
    bathrooms: 1,
    parkingSpots: 1,
    areaM2: 65,
    rentPrice: 3100,
    condoFee: 520,
    iptu: 130,
    status: 'AVAILABLE',
    listingType: 'RENT',
  },
  {
    id: '14',
    title: 'Studio novo — Tijuca',
    description: 'Studio em prédio novo, próximo à Praça Saens Peña.',
    type: 'STUDIO',
    street: 'Rua Conde de Bonfim',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '20520-053',
    bedrooms: 1,
    bathrooms: 1,
    parkingSpots: 0,
    areaM2: 30,
    salePrice: 420000,
    condoFee: 300,
    iptu: 65,
    status: 'AVAILABLE',
    listingType: 'SALE',
  },
  {
    id: '15',
    title: 'Apartamento familiar — Recreio dos Bandeirantes',
    description: 'Três quartos, próximo à praia e a escolas.',
    type: 'APARTMENT',
    street: 'Av. Lúcio Costa',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '22795-005',
    bedrooms: 3,
    bathrooms: 2,
    parkingSpots: 2,
    areaM2: 95,
    rentPrice: 3800,
    condoFee: 700,
    iptu: 180,
    status: 'AVAILABLE',
    listingType: 'RENT',
  },
  {
    id: '16',
    title: 'Casa térrea — Jacarepaguá',
    description: 'Casa térrea com quintal, ótima para famílias grandes.',
    type: 'HOUSE',
    street: 'Estrada do Tindiba',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '22730-100',
    bedrooms: 3,
    bathrooms: 2,
    parkingSpots: 2,
    areaM2: 130,
    salePrice: 650000,
    condoFee: 0,
    iptu: 160,
    status: 'AVAILABLE',
    listingType: 'SALE',
  },
  {
    id: '17',
    title: 'Apartamento econômico — Méier',
    description: 'Dois quartos, próximo ao comércio e à estação de trem.',
    type: 'APARTMENT',
    street: 'Rua Dias da Cruz',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '20720-001',
    bedrooms: 2,
    bathrooms: 1,
    parkingSpots: 1,
    areaM2: 58,
    rentPrice: 1750,
    condoFee: 350,
    iptu: 75,
    status: 'AVAILABLE',
    listingType: 'RENT',
  },
  {
    id: '18',
    title: 'Studio mobiliado — Flamengo',
    description: 'Studio mobiliado com vista para o Parque do Flamengo.',
    type: 'STUDIO',
    street: 'Rua Marquês de Abrantes',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '22230-060',
    bedrooms: 1,
    bathrooms: 1,
    parkingSpots: 0,
    areaM2: 38,
    salePrice: 580000,
    condoFee: 480,
    iptu: 95,
    status: 'AVAILABLE',
    listingType: 'SALE',
  },
]
