import type { Property } from './property';

export const propertiesMock: Property[] = [
  {
    id: '1',
    title: 'Apto moderno com varanda gourmet — Vila Madalena',
    description: 'Apartamento reformado com varanda gourmet, próximo ao metrô.',
    type: 'APARTMENT',
    street: 'Rua Harmonia',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '05435-000',
    bedrooms: 3,
    bathrooms: 2,
    parkingSpots: 1,
    areaM2: 85,
    rentPrice: 3000,
    condoFee: 450,
    iptu: 120,
    status: 'AVAILABLE',
  },
  {
    id: '2',
    title: 'Studio compacto e luminoso na Faria Lima',
    description: 'Studio bem localizado, ideal para quem trabalha na região.',
    type: 'STUDIO',
    street: 'Av. Faria Lima',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '05426-100',
    bedrooms: 1,
    bathrooms: 1,
    parkingSpots: 1,
    areaM2: 42,
    rentPrice: 2800,
    condoFee: 780,
    iptu: 90,
    status: 'AVAILABLE',
  },
  {
    id: '3',
    title: 'Apartamento reformado próximo ao metrô Sumaré',
    description: 'Dois quartos, reformado, próximo ao metrô Sumaré.',
    type: 'APARTMENT',
    street: 'Rua Sumaré',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01254-000',
    bedrooms: 2,
    bathrooms: 1,
    parkingSpots: 1,
    areaM2: 68,
    rentPrice: 2900,
    condoFee: 540,
    iptu: 100,
    status: 'AVAILABLE',
  },
]